# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 60e38e1d0506fad14fc3aba11cd3c175f975c2aa0f0380f1989c5c574c12fa02affac714e60e5ba08810d4ae5e5c692ad6b8a03a303cb28e0a35790388b58e92

test:
  secret_key_base: 27ba6263efbf879cf96b07d51a3a870a343565f0521ab0c783aa8aff4c0acd8f7ac1d87a1c4894a770f2efe76c35f7e98842c241bf4498170a24f9e5b0b42e9f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
